# Generated by Django 4.1.1 on 2022-10-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
