# Generated by Django 4.1.1 on 2022-10-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_time_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cancel_service',
            field=models.BooleanField(default=False, verbose_name='Атмена услуги'),
        ),
    ]
