# Generated by Django 4.1.1 on 2022-09-28 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Additionally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Дополнительно',
                'verbose_name_plural': 'Дополнительно',
            },
        ),
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to='decoration/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Отделка',
                'verbose_name_plural': 'Отделка',
            },
        ),
        migrations.CreateModel(
            name='PoolCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('desctiption', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='pool_cat/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Виды бассейна',
                'verbose_name_plural': 'Вид бассейна',
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField(verbose_name='Ширина')),
                ('length', models.FloatField(verbose_name='Длина')),
                ('depth', models.FloatField(verbose_name='Глубина')),
                ('desctiption', models.TextField(verbose_name='Коментарий')),
                ('additionally', models.ManyToManyField(to='construction.additionally', verbose_name='Дополнительно')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.poolcat', verbose_name='Катигория')),
                ('decoration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.decoration', verbose_name='Отделка')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
