# Generated by Django 4.1.1 on 2022-10-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0003_pool_active_pool_time_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='cancel_construction',
            field=models.BooleanField(default=False, verbose_name='Отменить строительство'),
        ),
    ]
