# Generated by Django 4.1.1 on 2022-10-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_order_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_order',
            field=models.BooleanField(default=False, verbose_name='Отмена заказа'),
        ),
    ]
