# Generated by Django 4.1.1 on 2022-10-15 08:00

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='construction_images/')),
            ],
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Название сайта')),
                ('working_time_start', models.TimeField(null=True, verbose_name='Время открытия')),
                ('working_time_end', models.TimeField(null=True, verbose_name='Время закрытия')),
                ('working_date', multiselectfield.db.fields.MultiSelectField(choices=[('monday', 'Пн'), ('tuesday', 'Вт'), ('wednesday', 'Ср'), ('thursday', 'Чт'), ('friday', 'Пт'), ('saturday', 'Сб'), ('sundayВс', 'Вс')], max_length=150, null=True, verbose_name='Рабочии дни')),
                ('adress', models.CharField(max_length=250, null=True, verbose_name='Адресс')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Емайл')),
                ('phone', models.IntegerField(null=True, verbose_name='Телефон')),
                ('tw_link', models.URLField(null=True, verbose_name='Ссылка на twitter')),
                ('fe_link', models.URLField(null=True, verbose_name='Ссылка на facebook')),
                ('in_link', models.URLField(null=True, verbose_name='Ссылка на linkedin')),
                ('sk_link', models.URLField(null=True, verbose_name='Ссылка на skype')),
            ],
            options={
                'verbose_name': 'Инфо',
                'verbose_name_plural': 'Инфо',
            },
        ),
    ]
