# Generated by Django 4.1.1 on 2022-09-30 09:23

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='construction_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='working_date',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('monday', 'Пн'), ('tuesday', 'Вт'), ('wednesday', 'Ср'), ('thursday', 'Чт'), ('friday', 'Пт'), ('saturday', 'Сб'), ('sundayВс', 'Вс')], max_length=150, null=True, verbose_name='Рабочии дни'),
        ),
    ]
